<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="ImiModel.NET.DeltaT" Version="1.0.0" />
    </ItemGroup>
    
</Project>
